export const ThemeLight = {
  fondo: "fff",
  color: "black",
  slogan: "#0074EF",
  contenedorSkill: "#181a1b",
  contenedorSkillHover: "#181a2b",
  formulario: "rgb(189, 184, 184)",
  footer: "fff",
  menu: "silver",
  cardCursos: "rgb(189, 184, 184)",
  cardCursosHover: "grey",
  hr: "black",
  borderReloj: "solid 1px grey",
  menuBG: "greenyellow",
  menuColor: "white",
  barraMenu: "silver",
  yo: "solid 2px silver",
  yoBox: "0px 0px 20px 5px rgba(12, 1, 219, 0.15)",
};

export const ThemeDark = {
  fondo: "black",
  color: "white",
  slogan: "aquamarine",
  contenedorSkill: "#181a1b",
  formulario: "black",
  footer: "black",
  menu: "red",
  cardCursos: "#181a1b",
  cardCursosHover: "#181a2b",
  hr: "white",
  borderReloj: "solid 1px white",
  menuBG: "greenyellow",
  menuColor: "black",
  curriculum: "white",
  barraMenu: "#181a2b",
  contenedorSkillHover: "  #181a2b",
  yo: "solid 2px white",
  yoBox: "0px 0px 20px 5px rgba(224, 219, 219, 0.15)",
};
